# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `username` variable needs to be provided to this playbook, via --extra-vars"
  when: "username is not defined or username == '<username>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `password` variable needs to be provided to this playbook, via --extra-vars"
  when: "password is not defined or password == '<password>'"

- name: Ensure Mosquitto is started
  ansible.builtin.service:
    name: "{{ mosquitto_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the Mosquitto instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Create user account
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} exec {{ mosquitto_identifier }} mosquitto_passwd -b {{ mosquitto_container_password_file_location }} {{ username | quote }} {{ password | quote }}"
