# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if playbook called incorrectly for Mosquitto
  ansible.builtin.fail:
    msg: "The `username` and `password` variable need to be provided to this playbook, via --extra-vars"
  when: >-
    username is not defined or username == 'USERNAME_HERE' or
    password is not defined or password == 'PASSWORD_HERE'

- name: Set user details for Mosquitto
  ansible.builtin.set_fact:
    user:
      username: "{{ username }}"
      password: "{{ password }}"
  no_log: true # hide raw password

- name: Ensure Mosquitto service is started
  ansible.builtin.service:
    name: "{{ mosquitto_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the Mosquitto instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: "Ensure Mosquitto user is created - {{ user.username }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/ensure_user_registered.yml"
  no_log: true

- name: Inject the message about the necessity of restarting the Mosquitto instance to activate the user
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: make sure to restart the service to activate the created user."
        ]
      }}
