# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `username` and `password` variable need to be provided to this playbook, via --extra-vars"
  when: >-
    username is not defined or username == 'USERNAME_HERE' or
    password is not defined or password == 'PASSWORD_HERE'

- name: Ensure Mosquitto service is started
  ansible.builtin.service:
    name: "{{ mosquitto_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the Mosquitto instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Create Mosquitto user account
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} exec {{ mosquitto_identifier }} mosquitto_passwd -b {{ mosquitto_container_password_file_location }} {{ username | quote }} {{ password | quote }}"

- name: Inject the message about the necessity of restarting the Mosquitto instance to activate the user
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: make sure to restart the service to activate the created user."
        ]
      }}
