# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Mosquitto paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ mosquitto_uid }}"
    group: "{{ mosquitto_gid }}"
  with_items:
    - "{{ mosquitto_base_path }}"
    - "{{ mosquitto_config_path }}"

- name: Ensure Mosquitto configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/mosquitto.conf.j2"
    dest: "{{ mosquitto_config_path }}/mosquitto.conf"
    owner: "{{ mosquitto_uid }}"
    group: "{{ mosquitto_gid }}"
    mode: 0640

- name: Ensure password file exists
  ansible.builtin.file:
    path: "{{ mosquitto_config_path }}/password_file"
    state: touch
    owner: "{{ mosquitto_uid }}"
    group: "{{ mosquitto_gid }}"
    mode: 0640

- name: Ensure Mosquitto container image is pulled
  community.docker.docker_image:
    name: "{{ mosquitto_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ mosquitto_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else mosquitto_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Mosquitto container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ mosquitto_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Mosquitto systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/mosquitto.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ mosquitto_identifier }}.service"
    mode: 0644
