# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: mosquitto_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: mosquitto_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-mosquitto
    - install-all
    - install-mosquitto

- block:
    - when: not mosquitto_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-mosquitto

- block:
    - when: mosquitto_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add-user.yml"
  tags:
    - mosquitto-add-user
