# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Mosquitto installation tasks
  when: mosquitto_enabled | bool
  tags:
    - setup-all
    - setup-mosquitto
    - install-all
    - install-mosquitto
  block:
    - name: Validate Mosquitto configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Mosquitto
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Mosquitto uninstallation tasks
  when: not mosquitto_enabled | bool
  tags:
    - setup-all
    - setup-mosquitto
  block:
    - name: Uninstall Mosquitto
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"

- name: Perform a task to add a user account to Mosquitto
  when: mosquitto_enabled | bool
  tags:
    - mosquitto-add-user
  block:
    - name: Add a user account
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add-user.yml"
