# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Mosquitto systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mosquitto_identifier }}.service"
  register: mosquitto_service_stat

- when: mosquitto_service_stat.stat.exists | bool
  block:
    - name: Ensure Mosquitto systemd service is stopped
      ansible.builtin.service:
        name: "{{ mosquitto_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Mosquitto systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mosquitto_identifier }}.service"
        state: absent

    - name: Ensure Mosquitto path does not exist
      ansible.builtin.file:
        path: "{{ mosquitto_base_path }}"
        state: absent
