# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Mosquitto systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mosquitto_identifier }}.service"
  register: mosquitto_service_stat

- name: Uninstall Mosquitto systemd service and scripts
  when: mosquitto_service_stat.stat.exists | bool
  block:
    - name: Ensure Mosquitto systemd service is stopped
      ansible.builtin.service:
        name: "{{ mosquitto_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Mosquitto systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mosquitto_identifier }}.service"
        state: absent

    - name: Ensure Mosquitto container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ mosquitto_container_network }}"
        state: absent

    - name: Ensure Mosquitto container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ mosquitto_container_network }}
      register: network_deletion_result
      changed_when: mosquitto_container_network in network_deletion_result.stdout

    - name: Ensure Mosquitto path does not exist
      ansible.builtin.file:
        path: "{{ mosquitto_base_path }}"
        state: absent
